openapi: '3.0.0'
info:
  version: 1.0.0
  title: Patrick Thauvette Documentation
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /shipowners:
    get:
      summary: List all shipowners
      operationId: listShipowners
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of shipowners
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipowners'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create shipowner
      operationId: createShipowner
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /shipowners/{ownerId}:
    get:
      summary: Info for a shipowner
      operationId: showShipownerById
      parameters:
        - name: ownerId
          in: path
          required: true
          description: The id of the shipowner to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipowners'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /regulations:
    get:
      summary: List all regulations
      operationId: listRegulations
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of regulations
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Regulations'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create regulation
      operationId: createRegulation
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /regulations/{regId}:
    get:
      summary: Info for regulation
      operationId: showRegulationById
      parameters:
        - name: regId
          in: path
          required: true
          description: The id of the regulation to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Regulations'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Shipowner:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        region:
          type: string
    Shipowners:
      type: array
      items:
        $ref: '#/components/schemas/Shipowner'
    Regulation:
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
        summary:
          type: string
    Regulations:
      type: array
      items:
        $ref: '#/components/schemas/Regulation'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string